"""Updated tables, added IncomeType

Revision ID: 1b063eccd164
Revises: 83d130a2c934
Create Date: 2023-07-16 16:15:52.024830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b063eccd164'
down_revision = '83d130a2c934'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'income_type_id')
    # ### end Alembic commands ###
