"""Updated actual and variance columns

Revision ID: 58af5aa2a86b
Revises: 07a63cb538c5
Create Date: 2023-07-18 07:55:39.339766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58af5aa2a86b'
down_revision = '07a63cb538c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
