"""Add date column to Income and Expense

Revision ID: 83d130a2c934
Revises: 
Create Date: 2023-07-16 08:48:05.711582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d130a2c934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('income', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'date')
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###
