"""Updated Category to Budget, category.name to budget.category and Expense.name to Expense.description

Revision ID: ada423c2cb9f
Revises: 58af5aa2a86b
Create Date: 2023-07-19 08:51:38.763705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada423c2cb9f'
down_revision = '58af5aa2a86b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.add_column('expenses', sa.Column('description', sa.String(length=100), nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'monthly_budget', ['category_id'], ['id'])
    op.drop_column('expenses', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'])
    op.drop_column('expenses', 'description')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('budget', sa.FLOAT(), nullable=True),
    sa.Column('actual', sa.FLOAT(), nullable=True),
    sa.Column('variance', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
