"""Added type to income table

Revision ID: c473958c6aa8
Revises: 1b063eccd164
Create Date: 2023-07-16 16:18:29.954605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c473958c6aa8'
down_revision = '1b063eccd164'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    # ### end Alembic commands ###
